services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "24678:24678"
    environment:
      - CHOKIDAR_USEPOLLING=true # helps dev file-watching in containers
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # helps dev file-watching in containers
    volumes:
      - ./backend/:/app
      - /app/node_modules
